### ISSUE TITLE
Compress using FLAC

### ISSUE THREAD

**Issue by JackKelly** [JackKelly/snd_card_power_meter#16]
I think the easiest way to do this might be something like this:
- split each audio recording into hour-long files
- when the time comes to create a new recording:
  - close the previous file
  - open a new file
  - first check the previous compression task completed.  Then subprocess to call ffmpeg to compress the previous recording to FLAC

There are Python audio libraries e.g.:
- http://pymedia.org/ (doesn't appear to have been updated since 2006)
- http://audiotools.sourceforge.net/ (last updated in late 2012.  Doesn't have entry on PyPI)
- https://github.com/jiaaro/pydub/ (updated recently and has entry on PyPI)

But I don't want to have to load the entire previous file into memory in Python.  Instead I want to just fire off an ffmpeg instance to compress the file.

**Comment by tomorrowbetter** [comment]
You may try this simple guide to compress M4A files with smaller file size but high quality at http://www.idealshare.net/audio-converter/audio-compressor-mac-windows.html

 

This guide also helps to compress other audio formats like compress FLAC, APE, WAV, AIFF, AU, RA, DTS, OGG, OPUS, CAF, WMA, AMR, etc.

 

It even can compress video files like compress MP4, MKV, AVI, FLV, MOV, AVCHD, MXF, DAV, etc.

**Comment by JackKelly** [comment]
@tomorrowbetter thank you, but I've settled on using `sox` to do compression on my Linux-based `snd_card_power_meter`.
