### ISSUE TITLE
A little BUG in /snd_card_power_meter/Scripts/convert_flac_to_dat.py <line #83>

### ISSUE THREAD

**Issue by nuaadot** [JackKelly/snd_card_power_meter#52]
In line #83 of the file mentioned above: there is "if not os.path.exists(args.input):"
but, this script' description is "Takes a whole directory of FLAC/WAV files and converts them
all to a single .DAT file.  Or can take a single file."
 If I take a single file to test ,there comes a problem.

Why do I say it's a bug? I take some examples:
>>> import os
>>> os.path.exists('/home/wh/my_test/vi-1388361600_508439')
False
>>> os.path.exists('/home/wh/my_test/vi-1388361600_508439.flac')
True
>>> os.path.exists('/home/wh/my_test/')
True

As you can see: I choose a single .flac file( a FLAC file without suffix instead of a directory) as input_filename when running the convert_flac_to_dat.py , 
an error comes out: "raise Exception("Input '{}' does not exist".format(args.input))"

I take another code to compare in /Scirpts/plot_flac.py "if not os.path.exists(flac_filename + '.wav'):"
in this way, you can handle the conflict between single .flac file as input_file and an error of "does not exists"

PS1. It is my first time to write a report in GitHub, so I wish Jack need not care too much if somewhere i am wrong or unreasonable.

PS2. On the other hand,  the script on the directory as input_file works well, Thanks Jack very much.

**Comment by JackKelly** [comment]
Thanks for your bug report, @nuaadot !  

I have changed the documentation so it now reads:

```
Takes a whole directory of FLAC/WAV files and converts them
all to a single .DAT file.  Or can take a single file 
(which must include the suffix).
```

Does that fix the problem for you?

If not, please feel free to provide a pull request.

**Comment by nuaadot** [comment]
yes, it works out.

Thanks Jack again.
